### PR TITLE
Auto-detect host OS, split out deploy playbooks for debian/rhel hosts

### PR DESCRIPTION
**Pull request by critzo**
PR #112 builds on the previous PRs working toward completion of Issue #98.

**This PR focuses only on splitting out playbook tasks by host OS.** It does not yet address the issue brought up in previous PRs about using a single set of system config files in `ansible/files/ ` rather than what we have currently (separate directory trees with files specific to each target OS, some of which are duplicates). **This will be addressed in an upcoming PR once the deployment is confirmed to work correctly on both target OSs.**

This PR adds a testing playbook, `deploy-piecewise-debian-test.yml` which will eventually replace `deploy-piecewise.yml`. This interim playbook detects the remote host OS and OS version, runs a separate playbook for Debian 8 hosts (`debian_hosts_tasks.yml`) or RHEL 7 hosts (`rhel_hosts_tasks.yml`), and then completes common tasks by running `all_hosts_tasks.yml`. 

Currently, this commit has been tested deploying a development Debian 8 host successfully. It has also been tested on a Centos7 host, though more work is necessary to end up with a running Piecewise instance on Centos7/RHEL hosts. The playbook successfully completes for a Centos host, but the Piecewise site is not immediately available post run. There is a misconfiguration that needs to be diagnosed in a subsequent PR.

---
This change is [Reviewable](https://reviewable.io/reviews/opentechinstitute/piecewise/112)

### CODE REVIEW

**Comment by nkinkade** [comment]
Hi Chris,

I added two small comments.

Thanks,

Nathan

---

Reviewed 10 of 11 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[ansible/playbooks/rhel_hosts_tasks.yml, line 41 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112#-KbQu7EcKB7985NO7BgT:-KbQu7EcKB7985NO7BgU:b-ibewha) ([raw file](https://github.com/opentechinstitute/piecewise/blob/60a4d3d21ae77172832c7d904314aaf9417aebec/ansible/playbooks/rhel_hosts_tasks.yml#L41)):*
> ```YAML
> - name: PostgreSQL not initialized - Initiate PostgreSQL database for RHEL 7 / Centos hosts
>   command: /usr/pgsql-9.4/bin/postgresql94-setup initdb
>   when: pginit.stat.exists == false
> ```

What are the circumstances where this conditional might evaluate to `false`? 

---

*[ansible/playbooks/rhel_hosts_tasks.yml, line 77 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112#-KbQuZUQ_HHw-v32QRC1:-KbQuZURKrAj0IpnfPXN:b-8bxbkr) ([raw file](https://github.com/opentechinstitute/piecewise/blob/60a4d3d21ae77172832c7d904314aaf9417aebec/ansible/playbooks/rhel_hosts_tasks.yml#L77)):*
> ```YAML
> ## Reload system daemons or services
> - name: Reload daemons for RHEL 7 / Centos systems
>   command: systemctl daemon-reload
> ```

Since 2.2, there is a [systemd Anisble module](https://docs.ansible.com/ansible/systemd_module.html) that can do this.  Are you using a version that will support using that module instead of the `command` module?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112#-:-KbQv0h2h0SRhDWMcpCO:b-9eong0)*

**Comment by critzo** [comment]
*[ansible/playbooks/rhel_hosts_tasks.yml, line 41 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112#-KbQu7EcKB7985NO7BgT:-KbR-vrbHCmKEyMz2NZd:b5ecan9) ([raw file](https://github.com/opentechinstitute/piecewise/blob/60a4d3d21ae77172832c7d904314aaf9417aebec/ansible/playbooks/rhel_hosts_tasks.yml#L41)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

What are the circumstances where this conditional might evaluate to `false`? 
</blockquote></details>

If the file /var/lib/pgsql/9.4/data/pg_hba.conf does not exist. Because I want to be able to run the playbook to deploy/update, I'm looking to begin adding checks for tasks that only need to be run once. For example, Postgres doesn't need to be initialized more than once, so this was a first attempt at a check to confirm whether it has been or not, and if not, this command is run. I'm still troubleshooting the install process for RHEL7/CentOS7 so this may not be the correct check. Need to confirm. In any case, without this check the first run of the playbook will succeed, but subsequent runs will fail at this step.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112)*

**Comment by critzo** [comment]
*[ansible/playbooks/rhel_hosts_tasks.yml, line 77 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112#-KbQuZUQ_HHw-v32QRC1:-KbR0se0bRZA7q82bTcl:b-sale4h) ([raw file](https://github.com/opentechinstitute/piecewise/blob/60a4d3d21ae77172832c7d904314aaf9417aebec/ansible/playbooks/rhel_hosts_tasks.yml#L77)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Since 2.2, there is a [systemd Anisble module](https://docs.ansible.com/ansible/systemd_module.html) that can do this.  Are you using a version that will support using that module instead of the `command` module?
</blockquote></details>

Good to know. I'll take a look at the systemd module. I have read that it's always better to use a module than issuing a direct command.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112)*

**Comment by nkinkade** [comment]
Add one new reply, with a possible strategy for introducing idempotency to `command` tasks.

---

Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/playbooks/rhel_hosts_tasks.yml, line 41 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112#-KbQu7EcKB7985NO7BgT:-KbR2ZwBR5Yw_cT-_FyR:b-4wrbnb) ([raw file](https://github.com/opentechinstitute/piecewise/blob/60a4d3d21ae77172832c7d904314aaf9417aebec/ansible/playbooks/rhel_hosts_tasks.yml#L41)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

If the file /var/lib/pgsql/9.4/data/pg_hba.conf does not exist. Because I want to be able to run the playbook to deploy/update, I'm looking to begin adding checks for tasks that only need to be run once. For example, Postgres doesn't need to be initialized more than once, so this was a first attempt at a check to confirm whether it has been or not, and if not, this command is run. I'm still troubleshooting the install process for RHEL7/CentOS7 so this may not be the correct check. Need to confirm. In any case, without this check the first run of the playbook will succeed, but subsequent runs will fail at this step.
</blockquote></details>

Perhaps a more efficient way to get around this issue of idempotency is to the `creates` parameter of the [`command` module](http://docs.ansible.com/ansible/command_module.html):

```
- name: PostgreSQL not initialized - Initiate PostgreSQL database for RHEL 7 / Centos hosts
  command: /usr/pgsql-9.4/bin/postgresql94-setup initdb
  creates: /var/lib/pgsql/9.4/data/pg_hba.conf
```

With that, I think you can eliminate the `Check whether PostegreSQL has been initialized` task.

What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112#-:-KbR3ShNpeCZYzpsh1ML:b-oh584x)*

**Comment by critzo** [comment]
*[ansible/playbooks/rhel_hosts_tasks.yml, line 41 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112#-KbQu7EcKB7985NO7BgT:-KbR99_CVzMAMhrwO7st:b-x2wtps) ([raw file](https://github.com/opentechinstitute/piecewise/blob/60a4d3d21ae77172832c7d904314aaf9417aebec/ansible/playbooks/rhel_hosts_tasks.yml#L41)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Perhaps a more efficient way to get around this issue of idempotency is to the `creates` parameter of the [`command` module](http://docs.ansible.com/ansible/command_module.html):

```
- name: PostgreSQL not initialized - Initiate PostgreSQL database for RHEL 7 / Centos hosts
  command: /usr/pgsql-9.4/bin/postgresql94-setup initdb
  creates: /var/lib/pgsql/9.4/data/pg_hba.conf
```

With that, I think you can eliminate the `Check whether PostegreSQL has been initialized` task.

What do you think?
</blockquote></details>

I can test this. For some reason I was thinking that the creates: line was there before. Does creates: basically function as a check on whether that file exists and if not creates it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112)*

**Comment by nkinkade** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/playbooks/rhel_hosts_tasks.yml, line 41 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112#-KbQu7EcKB7985NO7BgT:-KbRFHX2Cd-E6fonMkJ_:bay3cr8) ([raw file](https://github.com/opentechinstitute/piecewise/blob/60a4d3d21ae77172832c7d904314aaf9417aebec/ansible/playbooks/rhel_hosts_tasks.yml#L41)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

I can test this. For some reason I was thinking that the creates: line was there before. Does creates: basically function as a check on whether that file exists and if not creates it?
</blockquote></details>

I think so. From [the documentation](http://docs.ansible.com/ansible/command_module.html): _creates: a filename or (since 2.0) glob pattern, when it already exists, this step will **not** be run_

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112)*

**Comment by critzo** [comment]
*[ansible/playbooks/rhel_hosts_tasks.yml, line 71 at r3](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112#-KbRPjRAITzU2KOGEz-d:-KbRPjRAITzU2KOGEz-e:b-kjk6fd) ([raw file](https://github.com/opentechinstitute/piecewise/blob/721dd492f8039109dc2ce43505a6f6468c11e8bd/ansible/playbooks/rhel_hosts_tasks.yml#L71)):*
> ```YAML
>     mode: 0640
> 
> ## Reload system daemons or services
> ```

@nkinkade I decided to try using the service module to restart these instead of the systemd module after trying to use the systemd module along with with_items: which didn't seem to work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112)*

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ansible/playbooks/rhel_hosts_tasks.yml, line 41 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112#-KbQu7EcKB7985NO7BgT:-KbRVL-TeunPLInvYav5:b-fze3fb) ([raw file](https://github.com/opentechinstitute/piecewise/blob/60a4d3d21ae77172832c7d904314aaf9417aebec/ansible/playbooks/rhel_hosts_tasks.yml#L41)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I think so. From [the documentation](http://docs.ansible.com/ansible/command_module.html): _creates: a filename or (since 2.0) glob pattern, when it already exists, this step will **not** be run_
</blockquote></details>

To clarify my reply to your comment.  `creates:` just tells the command module that such and path (could be file or directory, I think) is created by the command in question. If that file already exists, then it skips the command. I can imagine that you could have a command that creates 10,000 files, but you tell Ansible that it creates any one of those 10,000 and it will skip the command.  The change you made LGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/112#-:-KbRVsKYIyupmd063q2a:bnfp4nl)*

**Pull request merged**
