### PR TITLE
Ansible refactor interim PR #5 of 7 - Move system files from conf/ to ansible/files/ and add rhel7 specific configs

### PR DESCRIPTION
**Pull request by critzo**
This is PR # 5 of 7 

To be more consistent with Ansible best practices, this PR moves system configuration files currently in conf/ into ansible/files, and group them into three sub-folders: common, debian8, and rhel7. Some files are common to all target hosts, and others are specific to debian8 or rhel7. Some of these files are new (those in the rhel7 folder). We've discussed merging these into a single directory at a future date, but for now, we'll separate them for convenience. These files will get copied to the remote server by Ansible playbooks.

---
This change is [Reviewable](https://reviewable.io/reviews/opentechinstitute/piecewise/122)

### CODE REVIEW

**Comment by critzo** [comment]
LGTM provided by @nkinkade and @georgiamoon via code-reviews list.

**Comment by georgiamoon** [comment]
@critzo -- i'm not sure @nkinkade  or I looked at this PR yet, @nkinkade's email was about #121

**Comment by nkinkade** [comment]
LGTM. To be sure, I'm not going over these with an ultra fine-toothed comb. I look for obvious errors or omissions, and trust that it will all come together when it's done. I think we can get down to something more detailed (in terms of reviews) once it's all together and we start tweaking things to hone the configuration and functioning of this.

**Comment by critzo** [comment]
Ok. my mistake @georgiamoon . Sorry about that! Agreed @nkinkade We definitely want a more thorough review. Thanks.

**Pull request merged**
