### PR TITLE
Add templates for Piecewise front-end website files

### PR DESCRIPTION
**Pull request by critzo**
PR #110 builds on the two previous, working toward issue #98. This PR adds variables and templates for the webpage provided by piecewise, the map_center, the piecewise system configuration file. A number of files no longer needed have been deleted, mostly because they were replaced with templates. 

Note that while most elements of the index page have been templated, the html form elements on the index page are not yet, but are included using a separate template file called `html_form`. The intention is to eventually replace this include file with variables in `piecewise_global_config.yml` and additional template loops in the index.html template. Database related code in the files `/local_customizations/extra_data.py` and `/collector/collector/wsgi.py` will also be templated in future PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/opentechinstitute/piecewise/110)

### CODE REVIEW

**Comment by nkinkade** [comment]
I've made a first pass, Chris.

---

Reviewed 15 of 19 files at r1.
Review status: 14 of 17 files reviewed at latest revision, 10 unresolved discussions.

---

*[ansible/group_vars/all/piecewise_global_config.yml, line 160 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLX1dX4gMfDfGu-r2Q:-KbLX1dX4gMfDfGu-r2R:b-4zg6c9) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/group_vars/all/piecewise_global_config.yml#L160)):*
> ```YAML
> 
> # If you are using a Mapbox base layer, set the API URL for your Mapbox tiles here.
> mapscript_mapbox_api_url: "https://api.mapbox.com/styles/v1/newamerica/ciy31olzw00792sp6w98b76i0/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoibmV3YW1lcmljYSIsImEiOiIyM3ZnYUtrIn0.57fFgg_iM7S1wLH2GQC71g"
> ```

Could it be better to genericize this variable to read something like `mapscript_tile_api_url` or similar?  Or are you planning to later add a `mapscript_osm_api_url` variable?  Also I see that the `mapscript_base_layer` is set to `osm`, but I don't see any API URL for OSM.

---

*[ansible/group_vars/all/piecewise_global_config.yml, line 224 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLZs9J2WcWWqvs8XbF:-KbLZs9J2WcWWqvs8XbG:b-te7gdl) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/group_vars/all/piecewise_global_config.yml#L224)):*
> ```YAML
> test_result_heading: "Your test results"
> download_result_label: "Download speed:"
> download_result_unit: "mbps"
> ```

Would this be more consistent with other labels we use around M-Lab as `Mbps` (captial M)?

---

*[ansible/group_vars/all/piecewise_global_config.yml, line 244 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLXgJO2QyI9L3pQWhr:-KbLXgJO2QyI9L3pQWhs:b9fmri3) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/group_vars/all/piecewise_global_config.yml#L244)):*
> ```YAML
> #
> # If you set any of these to 'none', they will be excluded from the website.
> # If you don't wnat any social share options, set all of the items below to 'none'
> ```

s/wnat/want/

---

*[ansible/templates/html_form, line 44 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLYQhAwUuGFPLN45TH:-KbLYQhAwUuGFPLN45TI:b-naak7j) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/html_form#L44)):*
> ```
> 						<p>Upload:</p>
> 						<input name="advertised_upload" size="3"/><small> mbps</small>
> 					</div><div class="expected-values">
> ```

Formatting nit: These divs don't appear to be indented correctly.

---

*[ansible/templates/index.html, line 9 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLYutDg-ykJU3VrjuJ:-KbLYutDg-ykJU3VrjuK:b-2if4tc) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L9)):*
> ```HTML
> 	<title>{{ site_name }}</title>
> 	<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
> 	<link href='https://api.tiles.mapbox.com/mapbox.js/v2.1.6/mapbox.css' rel='stylesheet' />
> ```

Many of the CSS and JS files included here are specific to Mapbox. Do you plan to make all these variable in some future PR so that users can use OSM without bringing in all the Mapbox stuff?

---

*[ansible/templates/index.html, line 96 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbL_Cj0bjbDPwGFHCYT:-KbL_Cj0bjbDPwGFHCYU:bwaqrs7) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L96)):*
> ```HTML
> 							    <i class="fa fa-google-plus"></i>
> 								</a>
> 							{% endif %}
> ```

Are there some indention issue from this point down? This `{% endif %}` doesn't seem to align with its start, nor the ones below.

---

*[ansible/templates/index.html, line 278 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbL_x8MYqMnOATWJZ3w:-KbL_x8MYqMnOATWJZ3x:b8ezsr9) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L278)):*
> ```HTML
> 	'{{ mapscript_layer_name }}': {
> 		'name': '{{ mapscript_layer_name_pretty }}',
> 		'polygonFile': 'geofiles/{{ topojson_file }}',
> ```

Question: The file will be located at `local_customizations/geofiles`, right? Is the directory `local_customizations/` the webroot?

---

*[ansible/templates/index.html, line 304 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLbD5gjh3zK-j9OF1v:-KbLbD5gjh3zK-j9OF1w:b-kej3sy) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L304)):*
> ```HTML
> {% set map_center -%}
> 	{{ map_center_lat|replace("(","") }}, {{ map_center_lon|replace(")","") }}
> {%- endset %}
> ```

Is the above a duplication of the file `map_center.js`?

---

*[ansible/templates/index.html, line 340 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLazKmRAlvL7FOQ5VW:-KbLazKmRAlvL7FOQ5VX:b-3tp3dt) ([raw file](https://github.com/opentechinstitute/piecewise/blob/2b5bfbc3f98c80a55e85ab3264384172c13a7992/ansible/templates/index.html#L340)):*
> ```HTML
> // if not then just set it to the center of the USA.
> if ( typeof center == 'undefined' ) {
> 	var center = [38.8961302513129,-99.04025268554688]; //USA
> ```

This was meant to act as a fall-back, just in case `center` wasn't defined. Is removing this fallback and setting it to `{{ map_center }}` still going to provide fallback? We may not care about fallback?

---

*[ansible/templates/index.html, line 382 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLbjPX7BIP5FXf3j_O:-KbLbjPX7BIP5FXf3j_P:bwmmxrg) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L382)):*
> ```HTML
> 
> // Set the base tile layer type
> {% if 'mapbox' in mapscript_base_layer %}
> ```

Should this be checking for equality instead of inclusion? The comment above `mapscript_base_layer` says that it should be one thing or the other. Maybe I don't know enough about Jinja2 templating.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-:-KbLcGuKvFmuF4NWmS7e:bat56nc)*

**Comment by critzo** [comment]
*[ansible/group_vars/all/piecewise_global_config.yml, line 160 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLX1dX4gMfDfGu-r2Q:-KbLhFz5LM97-XBT-95k:b9ey2ii) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/group_vars/all/piecewise_global_config.yml#L160)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Could it be better to genericize this variable to read something like `mapscript_tile_api_url` or similar?  Or are you planning to later add a `mapscript_osm_api_url` variable?  Also I see that the `mapscript_base_layer` is set to `osm`, but I don't see any API URL for OSM.
</blockquote></details>

I think that keeping a url var specific to each map tile api that has been tested is better. Just adding the osm_api url variable would provide the option to change to a custom osm url, like if someone already runs a tile server. The other reason to keep them separate (not a single tile_url var) is that some providers might have more variable requirements than others. This could be changed in the future of course.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by critzo** [comment]
*[ansible/group_vars/all/piecewise_global_config.yml, line 224 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLZs9J2WcWWqvs8XbF:-KbLiRMQkAVTzT0RSntQ:b-gsixkd) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/group_vars/all/piecewise_global_config.yml#L224)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Would this be more consistent with other labels we use around M-Lab as `Mbps` (captial M)?
</blockquote></details>

This is a user-customizable choice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by critzo** [comment]
*[ansible/templates/index.html, line 9 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLYutDg-ykJU3VrjuJ:-KbLjf4TLjZ7IaCakw-T:bklhgaj) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L9)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Many of the CSS and JS files included here are specific to Mapbox. Do you plan to make all these variable in some future PR so that users can use OSM without bringing in all the Mapbox stuff?
</blockquote></details>

Good call. I can add this logic to the index page template to only load the resources needed for the selected provider.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by critzo** [comment]
*[ansible/templates/index.html, line 96 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbL_Cj0bjbDPwGFHCYT:-KbLkW_2s300vYsSCl9e:b-padng2) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L96)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Are there some indention issue from this point down? This `{% endif %}` doesn't seem to align with its start, nor the ones below.
</blockquote></details>

I think this is a difference in display per editor used to view the file. In Sublime text, these indents are all aligned as expected, but I'll re-do them to make sure they're exactly the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by critzo** [comment]
*[ansible/templates/index.html, line 278 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbL_x8MYqMnOATWJZ3w:-KbLlBWAlGAJfL6yOw6d:b-qb4nde) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L278)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Question: The file will be located at `local_customizations/geofiles`, right? Is the directory `local_customizations/` the webroot?
</blockquote></details>

No, /opt/piecewise_web/ is still the webroot.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by critzo** [comment]
*[ansible/templates/index.html, line 304 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLbD5gjh3zK-j9OF1v:-KbLlhUDyQYk_rl5loro:bz2l8d) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L304)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is the above a duplication of the file `map_center.js`?
</blockquote></details>

Yes. The duplication is necessary in each template to calculate the map center coordinates. If you have a suggestion on how to do it in the config file, I'd love to have the contribution. Before doing it this way, I tried doing the calculation in the main config file but couldn't find a way to do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by critzo** [comment]
*[ansible/templates/index.html, line 340 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLazKmRAlvL7FOQ5VW:-KbLmb83t7esTXMaVrc8:b-f0i65) ([raw file](https://github.com/opentechinstitute/piecewise/blob/2b5bfbc3f98c80a55e85ab3264384172c13a7992/ansible/templates/index.html#L340)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

This was meant to act as a fall-back, just in case `center` wasn't defined. Is removing this fallback and setting it to `{{ map_center }}` still going to provide fallback? We may not care about fallback?
</blockquote></details>

Perhaps we don't care about the fallback. I'm not sure about the rationale for it really since we're always going to have a center point. The app won't deploy without coordinates for the bounding box, and the center is now calculated from them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by critzo** [comment]
*[ansible/templates/index.html, line 382 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLbjPX7BIP5FXf3j_O:-KbLnEd7UBVLATU_KeGD:b-jpi2fi) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L382)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Should this be checking for equality instead of inclusion? The comment above `mapscript_base_layer` says that it should be one thing or the other. Maybe I don't know enough about Jinja2 templating.
</blockquote></details>

Yeah, I tried that. The options available in Jinja2 templating are different in some cases. You might think for example that {% if mapscript_base_layer is equalto 'mapbox %} would work, but it doesn't for strings.  http://jinja.pocoo.org/docs/2.9/templates/#builtin-tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by critzo** [comment]
*[ansible/templates/index.html, line 9 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLYutDg-ykJU3VrjuJ:-KbLxCUWzePN6c86BckX:bjcevsw) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L9)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

Good call. I can add this logic to the index page template to only load the resources needed for the selected provider.
</blockquote></details>

Follow up- I tried this but then the map base layers failed to load. Apparently we're using the Leaflet libraries that are in the mapbox JS regardless of base layer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by nkinkade** [comment]
I've replied to some of your comments.

---

Review status: 14 of 17 files reviewed at latest revision, 7 unresolved discussions.

---

*[ansible/group_vars/all/piecewise_global_config.yml, line 160 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLX1dX4gMfDfGu-r2Q:-KbLwUQmCrlus-Jl8D7l:b-6qikwh) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/group_vars/all/piecewise_global_config.yml#L160)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

I think that keeping a url var specific to each map tile api that has been tested is better. Just adding the osm_api url variable would provide the option to change to a custom osm url, like if someone already runs a tile server. The other reason to keep them separate (not a single tile_url var) is that some providers might have more variable requirements than others. This could be changed in the future of course.
</blockquote></details>

Alright. Are you going to add the variable `mapscript_osm_api_url` now, or are you saving that for some future commit?

---

*[ansible/group_vars/all/piecewise_global_config.yml, line 224 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLZs9J2WcWWqvs8XbF:-KbLwq9qWP5yDmBbD9N4:b-6q7hi9) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/group_vars/all/piecewise_global_config.yml#L224)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

This is a user-customizable choice.
</blockquote></details>

It is, but this is designed to be a template, right? It seems like we'd want to put in the preferred acronyms, where possible. I'll leave that up to you, though.

---

*[ansible/templates/index.html, line 96 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbL_Cj0bjbDPwGFHCYT:-KbLxV1imLmARrHUgDZO:b-vf8rk) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L96)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

I think this is a difference in display per editor used to view the file. In Sublime text, these indents are all aligned as expected, but I'll re-do them to make sure they're exactly the same.
</blockquote></details>

It seems fixed now. Thanks.

---

*[ansible/templates/index.html, line 278 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbL_x8MYqMnOATWJZ3w:-KbLxft2snCkvwb4zvLo:b72sr7y) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L278)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

No, /opt/piecewise_web/ is still the webroot.  
</blockquote></details>

Okay, then I'll assume that making sure that `local_customizations/geofiles` is somehow copied or linked to `/opt/piecewise_web` at some previous step.

---

*[ansible/templates/index.html, line 304 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLbD5gjh3zK-j9OF1v:-KbM-rge9lwA8mE2OCMG:brzhcu1) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L304)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

Yes. The duplication is necessary in each template to calculate the map center coordinates. If you have a suggestion on how to do it in the config file, I'd love to have the contribution. Before doing it this way, I tried doing the calculation in the main config file but couldn't find a way to do it.
</blockquote></details>

Would it be possible to use an [include](http://jinja.pocoo.org/docs/2.9/templates/#include)`templates/map_center.js` here? Something like:

`{% include 'map_center.js' %}`

---

*[ansible/templates/index.html, line 340 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLazKmRAlvL7FOQ5VW:-KbLyL6ymmmtYJAQmSA7:b-ki6qfh) ([raw file](https://github.com/opentechinstitute/piecewise/blob/2b5bfbc3f98c80a55e85ab3264384172c13a7992/ansible/templates/index.html#L340)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

Perhaps we don't care about the fallback. I'm not sure about the rationale for it really since we're always going to have a center point. The app won't deploy without coordinates for the bounding box, and the center is now calculated from them.
</blockquote></details>

If that is the case, then you should be able to remove this `if` block.

---

*[ansible/templates/index.html, line 382 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLbjPX7BIP5FXf3j_O:-KbLzYrrt1h1PxY2EpUc:bnwcb24) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L382)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

Yeah, I tried that. The options available in Jinja2 templating are different in some cases. You might think for example that {% if mapscript_base_layer is equalto 'mapbox %} would work, but it doesn't for strings.  http://jinja.pocoo.org/docs/2.9/templates/#builtin-tests
</blockquote></details>

I would have expected that you could [a simple comparison operator](http://jinja.pocoo.org/docs/2.9/templates/#comparisons) instead of a built-in function. This doesn't work, for example:

`{% if mapscript_base_layer == 'mapbox' %}`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-:-KbM1tNCudtsOAqlqYUH:bip04e2)*

**Comment by critzo** [comment]
*[ansible/group_vars/all/piecewise_global_config.yml, line 160 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLX1dX4gMfDfGu-r2Q:-KbMPJYrM709nD7m0lPb:beyjryn) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/group_vars/all/piecewise_global_config.yml#L160)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Alright. Are you going to add the variable `mapscript_osm_api_url` now, or are you saving that for some future commit?
</blockquote></details>

I added it in the latest commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by critzo** [comment]
*[ansible/group_vars/all/piecewise_global_config.yml, line 224 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLZs9J2WcWWqvs8XbF:-KbMPXbZHgWJr4MMzlp9:b-c8h41v) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/group_vars/all/piecewise_global_config.yml#L224)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

It is, but this is designed to be a template, right? It seems like we'd want to put in the preferred acronyms, where possible. I'll leave that up to you, though.
</blockquote></details>

Well, the template uses the value that the user specifies here. If there's consensus that it should be Mbps then I can change the default value. I'll do that in a subsequent commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by critzo** [comment]
*[ansible/templates/index.html, line 278 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbL_x8MYqMnOATWJZ3w:-KbMQIwZ9xosHTTyZPra:by2yxsd) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L278)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Okay, then I'll assume that making sure that `local_customizations/geofiles` is somehow copied or linked to `/opt/piecewise_web` at some previous step.
</blockquote></details>

It is copied over in the system_tasks.yml playbook.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by critzo** [comment]
*[ansible/templates/index.html, line 304 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLbD5gjh3zK-j9OF1v:-KbMQQmX0SLKlv2nrWVm:b62fnzm) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L304)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Would it be possible to use an [include](http://jinja.pocoo.org/docs/2.9/templates/#include)`templates/map_center.js` here? Something like:

`{% include 'map_center.js' %}`
</blockquote></details>

True. I could do that. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by critzo** [comment]
*[ansible/templates/index.html, line 340 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLazKmRAlvL7FOQ5VW:-KbMl80d8rqCQBKg-rw4:bvxe66e) ([raw file](https://github.com/opentechinstitute/piecewise/blob/2b5bfbc3f98c80a55e85ab3264384172c13a7992/ansible/templates/index.html#L340)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

If that is the case, then you should be able to remove this `if` block.
</blockquote></details>

I will test removing the block to see if there are no unseen implications. Honestly I think going to be optimizing this code for some time, the JavaScript in particular. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by critzo** [comment]
*[ansible/templates/index.html, line 382 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLbjPX7BIP5FXf3j_O:-KbMl_U-yEEGo30Dqha1:bg1s6fs) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L382)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I would have expected that you could [a simple comparison operator](http://jinja.pocoo.org/docs/2.9/templates/#comparisons) instead of a built-in function. This doesn't work, for example:

`{% if mapscript_base_layer == 'mapbox' %}`
</blockquote></details>

I expected that too, but tried it and it doesn't work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Comment by nkinkade** [comment]
:lgtm:, with the note that we should figure out `{% somevar == 'value' %}` isn't working at some point rather than working around it.

---

Reviewed 1 of 19 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/templates/index.html, line 382 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLbjPX7BIP5FXf3j_O:-KbMq89GYrtDEembxCZx:bft87i1) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L382)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

I expected that too, but tried it and it doesn't work.
</blockquote></details>

ACKing that you've tried this and it doesn't seem to work, but also flagging that  we are likely doing something wrong it doesn't work. At some point we should try to get to the bottom of it instead of just working around it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-:-KbMqTLXPo79OQYuRSem:b-anhvg1)*

**Comment by critzo** [comment]
Thanks. @nkinkade . WRT your note, feel free to investigate. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-:-KbQDRGBPVBMF3GKbRJJ:bvk01ax)*

**Comment by critzo** [comment]
*[ansible/templates/index.html, line 382 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110#-KbLbjPX7BIP5FXf3j_O:-KbQDhsWvcpBmwUY1pIw:be2n5ki) ([raw file](https://github.com/opentechinstitute/piecewise/blob/ba1f543ea396974304933119180ac51fac4b6806/ansible/templates/index.html#L382)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

ACKing that you've tried this and it doesn't seem to work, but also flagging that  we are likely doing something wrong it doesn't work. At some point we should try to get to the bottom of it instead of just working around it.
</blockquote></details>

I'll add an issue about it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/110)*

**Pull request merged**
