### PR TITLE
Update to support Rhel7 hosts alongside Centos7 hosts

### PR DESCRIPTION
**Pull request by critzo**
This PR takes steps toward making Piecewise deployable to RHEL hosts directly rather than manually as was the case in Seattle. 

- Adds Ansible conditionals to detect `RedHat` hosts as well as ` CentOS`
- Moves extraction of Maxmind CSV into OS specific playbooks, since Debian requires the -j flag but CentOS/RHEL do not
- Begins to add requested changes from Seattle to the Rhel7 nginx conf file (See item 3 in #125)

---
This change is [Reviewable](https://reviewable.io/reviews/opentechinstitute/piecewise/126)

### CODE REVIEW

**Comment by nkinkade** [comment]
Hi Chris. I've added a few comments.

---

Reviewed 2 of 8 files at r1.
Review status: 2 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[ansible/deploy-piecewise.retry, line 0 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126#-KgVIhBEPOAFVyJVuPce:-KgVIhBEPOAFVyJVuPcf:bmg64n2) ([raw file](https://github.com/opentechinstitute/piecewise/blob/d976063844862508c6608c3ec8b9135f1c9f69c3/ansible/deploy-piecewise.retry#L0)):*
You might like to add something like `*.retry` to the the .gitignore file to avoid this ever happening again.

---

*[ansible/files/rhel7/etc/nginx/nginx.conf, line 20 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126#-KgVJ1UfjLlFpc_yiuQf:-KgVJ1UfjLlFpc_yiuQg:bvvjalb) ([raw file](https://github.com/opentechinstitute/piecewise/blob/d976063844862508c6608c3ec8b9135f1c9f69c3/ansible/files/rhel7/etc/nginx/nginx.conf#L20)):*
> ```Nginx
>     log_format  syslog_ng  '$remote_addr $server_name $remote_user "$http_user_agent" $time_local "$request"  $status $body_bytes_sent';
>     
>     syslog_ng_log /var/log/nginx/nginx_socket syslog_ng;
> ```

Just reiterating here what we chatted about this morning: I think it would be better to keep a standard/stock nginx config to the extent possible, and let Seattle make these changes to their own deployment.

---

*[ansible/inventory/debian8-hosts, line 1 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126#-KgVKv1R5oLiPdDw5eBP:-KgVKv1R5oLiPdDw5eBQ:bjxspzf) ([raw file](https://github.com/opentechinstitute/piecewise/blob/d9628203a925e7c28e8905d986fc5b0944577dec/ansible/inventory/debian8-hosts#L1)):*
> ```
> 104.197.237.109 ansible_ssh_user=critzo
> ```

Is your text editor (or git config) stripping the newlines from the end of files?

---

*[ansible/playbooks/all_hosts_tasks.yml, line 46 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126#-KgVMXsQdy0zIc0NnOWf:-KgVMXsQdy0zIc0NnOWg:bhofvou) ([raw file](https://github.com/opentechinstitute/piecewise/blob/d9628203a925e7c28e8905d986fc5b0944577dec/ansible/playbooks/all_hosts_tasks.yml#L46)):*
> - name: Get the latest MaxMind CSV
>   get_url:
>     url: http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum2.zip

---

*[ansible/playbooks/all_hosts_tasks.yml, line 55 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126#-KgVLbl-q7os-ehPB8y9:-KgVLbl-q7os-ehPB8yA:b3dv6jm) ([raw file](https://github.com/opentechinstitute/piecewise/blob/d9628203a925e7c28e8905d986fc5b0944577dec/ansible/playbooks/all_hosts_tasks.yml#L55)):*
> ```YAML
>     creates: /tmp/GeoIPASNum2.csv
>     remote_src: yes
> ```

Something seems strange to me here. I'm not sure why this would need the `-j` option. I just downloaded the [MaxMind database specified in the URL above](http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum2.zip), and its contents are a single file (GeoIPASNum2.csv). I can only imagine that there is something not quite right about the way the `unarchive` module is being invoked here.

How about something like the following, which also obviates the need for the `Get the latest MaxMind CSV` task? I just tried it to a Debian host (EB) and it worked as expected:

```
  - name: Unzip MaxMind CSV
    unarchive:
      remote_src: yes
      src: http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum2.zip
      dest: /tmp/
      creates: /tmp/GeoIPASNum2.csv
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126#-:-KgVOjpOBYgxHFxuddFq:b1peekv)*

**Comment by critzo** [comment]
*[ansible/files/rhel7/etc/nginx/nginx.conf, line 20 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126#-KgVJ1UfjLlFpc_yiuQf:-KgVQF6_GDeWWNDU_A2A:b6op16u) ([raw file](https://github.com/opentechinstitute/piecewise/blob/d976063844862508c6608c3ec8b9135f1c9f69c3/ansible/files/rhel7/etc/nginx/nginx.conf#L20)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Just reiterating here what we chatted about this morning: I think it would be better to keep a standard/stock nginx config to the extent possible, and let Seattle make these changes to their own deployment.
</blockquote></details>

Acknowledged. I'll remove this in a commit before moving on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126)*

**Comment by critzo** [comment]
*[ansible/inventory/debian8-hosts, line 1 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126#-KgVKv1R5oLiPdDw5eBP:-KgVQTWVpIQnYPQDwMGx:b-vjyq4o) ([raw file](https://github.com/opentechinstitute/piecewise/blob/d9628203a925e7c28e8905d986fc5b0944577dec/ansible/inventory/debian8-hosts#L1)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is your text editor (or git config) stripping the newlines from the end of files?
</blockquote></details>

I think this is me just being pedantic. I just deleted the final blank line in this case, which has the added effect of stripping the newline char.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126)*

**Comment by critzo** [comment]
*[ansible/playbooks/all_hosts_tasks.yml, line 55 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126#-KgVLbl-q7os-ehPB8y9:-KgVQsi80zxjs0ov_UUV:b29zral) ([raw file](https://github.com/opentechinstitute/piecewise/blob/d9628203a925e7c28e8905d986fc5b0944577dec/ansible/playbooks/all_hosts_tasks.yml#L55)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Something seems strange to me here. I'm not sure why this would need the `-j` option. I just downloaded the [MaxMind database specified in the URL above](http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum2.zip), and its contents are a single file (GeoIPASNum2.csv). I can only imagine that there is something not quite right about the way the `unarchive` module is being invoked here.

How about something like the following, which also obviates the need for the `Get the latest MaxMind CSV` task? I just tried it to a Debian host (EB) and it worked as expected:

```
  - name: Unzip MaxMind CSV
    unarchive:
      remote_src: yes
      src: http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum2.zip
      dest: /tmp/
      creates: /tmp/GeoIPASNum2.csv
```
</blockquote></details>

I'll test that on a Debian and RHEL7 host to confirm.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126)*

**Comment by nkinkade** [comment]
Review status: 2 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[ansible/inventory/debian8-hosts, line 1 at r1](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126#-KgVKv1R5oLiPdDw5eBP:-KgVUDgH7_2vR-XOAPgU:bir4pwl) ([raw file](https://github.com/opentechinstitute/piecewise/blob/d9628203a925e7c28e8905d986fc5b0944577dec/ansible/inventory/debian8-hosts#L1)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

I think this is me just being pedantic. I just deleted the final blank line in this case, which has the added effect of stripping the newline char.
</blockquote></details>

I think the final blank line is not the issue, but the missing NL character at the end of the existing line. My understanding is that it is a POSIX compliance requires a NL character at the end of every line, including the last one.  And apparently C (and maybe others) require this:

http://stackoverflow.com/questions/5813311/no-newline-at-end-of-file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126)*

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r1, 5 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/piecewise/126#-:-KgWGmfU-0jkZPQC2XMV:bnfp4nl)*

**Pull request merged**
