### PR TITLE
Add MLab data to <InfoPanel /> table view

### PR DESCRIPTION
**Pull request by jeremiak**
Represent the MLab data in the tabular view within the `<InfoPanel />` component so that the narrative and table views have information parity.

Screen Shot 2020-12-01 at 2 44 39 PM

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/piecewise/204)

### CODE REVIEW

**Comment by critzo** [comment]
@jeremiak 
On first building this branch in Docker, I had a couple issues:
- Docker build does not complete successfully with `/src/vectortiles` in the repo. Moving it out of the repo enables the Docker containers to be built successfully, but the resulting service doesn't contain the Map tab at all
- I'm currently running `make piecewise` from the `/src/vectortiles` folder on a VM, but wonder --
  * Is it necessary to build the tiles from this repo if they are hosted in GCS?
  * Does `/src/vectortiles` need to be present in this repo for the map tab to show up?

**Comment by jeremiak** [comment]
@critzo There's no reason the `/src/vectortiles` "codebase" has to be within this repo at all. The `Makefile` process finishes with the vectortiles being uploaded to GCS, which is [where the <MapTab /> looks for them](https://github.com/m-lab/piecewise/blob/master/src/frontend/components/dashboard/MapTab/mapboxStyle.js#L22).

I will note that if you moved that process to another repo, that it has some Node based dependencies that you'll want to make sure to include in that repo's `package.json`. From looking through that code, the dependencies will be:

1. `mapshaper`
1. `p-queue`
1. `wget-improved`
1. `csv`
1. `sqlite`
1. `sqlite3`
1. `d3@v5`
1. `glob`

There shouldn't be any connection between including the vectortiles code in the repo and the map tab showing up on the web application. I'll go ahead and try and replicate that locally.

**Comment by critzo** [comment]
This morning I've pulled a fresh of `m-lab/piecewise` andhave built it from `master` using the Docker commands in the Readme, previewing it locally. Below are screenshots. I made a change to `package.json` so eslint doesn't do anything with `src/vectortiles` in the Docker build. Question @jeremiak Are the screenshots showing anything different than what should be seen in `jeremiak/info-panel-table` ? I will next do a local merge of that branch, re-build and re-test.

image
image
image

**Review by critzo — APPROVED** [review]
Rebuilding this with a local merge of the forked branch now works fine. I'll make a follow up commit to keep eslint from checking `src/vectortiles`

LGTM.

**Pull request merged**
